<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Mahesh-DT" failures="0" tests="2" name="InterviewPerspectiveSel.DependsOnFail" time="2.027" errors="1" timestamp="2025-05-17T15:46:42 IST" skipped="0">
  <testcase classname="InterviewPerspectiveSel.DependsOnFail" name="loveMarriage" time="0.002"/>
  <testcase classname="InterviewPerspectiveSel.DependsOnFail" name="parentsPermission" time="2.025">
    <error message="Method InterviewPerspectiveSel.DependsOnFail.parentsPermission() didn&#039;t finish within the time-out 2000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method InterviewPerspectiveSel.DependsOnFail.parentsPermission() didn't finish within the time-out 2000
at java.base/java.lang.Thread.sleep0(Native Method)
at java.base/java.lang.Thread.sleep(Thread.java:509)
at InterviewPerspectiveSel.DependsOnFail.parentsPermission(DependsOnFail.java:9)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </error>
  </testcase> <!-- parentsPermission -->
</testsuite> <!-- InterviewPerspectiveSel.DependsOnFail -->
